django_apps/clinica/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name = 'clinica'

urlpatterns = [
    #Lista de Propietarios
    url(r'^propietarios/$', views.ClienteClinico.as_view(), name='propietarios'),
    #Busquedas
    url(r'^buscar-propietario/$', views.search_propietario, name='buscar_propietario'),
    url(r'^(?P<cliente_slug>[\w-]+)/buscar-mascota/$', views.search_mascota, name='buscar_mascota'),
    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/buscar-historial/$', views.search_historial, name='buscar_historial'),
    # Mantenimiento de Mascotas del cliente o propietario
    url(r'^(?P<cliente_slug>[\w-]+)/mascotas/$', views.ListaMascotas.as_view(), name='listar_mascotas'),
    url(r'^(?P<cliente_slug>[\w-]+)/agregar-mascota/$', views.NuevaMascota, name='agregar_mascota'),
    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/$', views.DetalleMascota.as_view(), name='detalle_mascota'),
    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/editar/$', views.EditarMascota, name='editar_mascota'),
    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/eliminar/$', views.EliminarMascota.as_view(), name='eliminar_mascota'),
    # url(r'^(?P<cliente_slug>[\w-]+)/nueva-mascota/$', views.NuevaMascota.as_view(), name='nueva_mascota'),
    # url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/editar/$', views.EditarMascota.as_view(), name='editar_mascota'),

    # Mantenimiento de Estados de las mascotas de los clientes
    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/historial/$',
        views.HistorialMascota.as_view(), name='historial_mascota'),

    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/nuevo-historial/$',
        views.NuevoEstadoMascota.as_view(), name='nuevo_estado_mascota'),

    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/(?P<estado_slug>[\w-]+)/$',
        views.DetalleEstadoMascota.as_view(), name='detalle_estado_mascota'),

    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/(?P<estado_slug>[\w-]+)/editar/$',
        views.EditarEstadoMascota.as_view(), name='editar_estado_mascota'),

    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/(?P<estado_slug>[\w-]+)/eliminar/$',
        views.EliminarEstadoMascota.as_view(),name='eliminar_estado_mascota'),
]

django_apps/home/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
from django.conf import settings
from django.contrib.auth.forms import AdminPasswordChangeForm
from django.core.urlresolvers import reverse_lazy
from . import views

app_name = 'home'

urlpatterns = [
    ## Gestion de usuarios
    url(r'^login/$', views.Login.as_view(), name='login_empleado'),
    url(r'^logout/$', views.Logout.as_view(), name='logout_empleado'),
    url(r'^veterinaria/$', views.ControlPanelVeterinaria.as_view(), name='inicio'),
    url(r'^empleados/$', views.ListaEmpleados.as_view(), name='listar_empleados'),
    url(r'^search-empleado/$', views.search_empleado, name="buscar_empleado"),
    url(r'^signup/$', views.CrearEmpleado.as_view(), name='signup_empleado'),
    url(r'^(?P<empleado_slug>[\w-]+)/$', views.DetalleEmpleado.as_view(), name='detalle_empleado'),

    #Cambiar Usuario creado
    # url(r'^usuario/(?P<pk>[0-9]+)/editar/$', views.EditUser,
    #     name="editar_user"),
    url(r'^(?P<empleado_slug>[\w-]+)/editar/$', views.EditarEmpleado.as_view(),
        name="editar_empleado"),

    url(r'^(?P<empleado_slug>[\w-]+)/eliminar/$', views.EliminarEmpleado.as_view(),
        name="eliminar_empleado"),
    # Cambiar Contraseña de usuario
    # url(r'^usuarios/', include('django.contrib.auth.urls')),
    url(r'^(?P<empleado_slug>[\w-]+)/password_change/$', views.password_change,
        name="password_change"),

]

django_apps/persona/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name = 'persona'

urlpatterns = [
    url(r'^search-cliente/$', views.search_cliente, name="buscar_cliente"),
    url(r'^clientes/$', views.ListaClientes.as_view(), name='listar_clientes'),
    url(r'^cliente/crear/$', views.CrearCliente.as_view(), name='crear_cliente'),
    url(r'^cliente/(?P<cliente_slug>[\w-]+)/$', views.DetalleCliente.as_view(), name='detalle_cliente'),
    url(r'^cliente/(?P<cliente_slug>[\w-]+)/editar/$', views.EditarCliente.as_view(), name='editar_cliente'),
    url(r'^cliente/(?P<cliente_slug>[\w-]+)/eliminar/$', views.EliminarCliente.as_view(), name='eliminar_cliente'),

    url(r'^search-proveedor/$', views.search_proveedor, name="buscar_proveedor"),
    url(r'^proveedores/$', views.ListaProveedores.as_view(), name='listar_proveedores'),
    url(r'^proveedor/crear/$', views.CrearProveedor.as_view(), name='crear_proveedor'),
    url(r'^proveedor/(?P<proveedor_slug>[\w-]+)/$', views.DetalleProveedor.as_view(), name='detalle_proveedor'),
    url(r'^proveedor/(?P<proveedor_slug>[\w-]+)/editar/$', views.EditarProveedor.as_view(), name='editar_proveedor'),
    url(r'^proveedor/(?P<proveedor_slug>[\w-]+)/eliminar/$', views.EliminarProveedor.as_view(), name='eliminar_proveedor'),
]

django_apps/ventas/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'ventas'

urlpatterns = [
    url(r'^(?P<venta_pk>[0-9]+)/editar-venta/$', views.UpdateVenta, name='update_venta'),
    url(r'^$', views.ListaVentas.as_view(), name='listar_ventas'),
    url(r'^search-venta/$', views.search_venta, name='buscar_venta'),
    # url(r'^nuevo/$', views.NuevaVenta, name='nueva_venta'),
    url(r'^nueva-venta/$', views.CreateVenta, name='venta_nueva'),
    #
    url(r'^(?P<venta_pk>[0-9]+)/$', views.DetalleVenta.as_view(), name='detalle_venta'),
    #PDF Venta
    url(r'^(?P<venta_pk>[0-9]+)/venta-pdf/$', views.VentaPDF.as_view(), name='pdf_venta'),
    # url(r'^(?P<venta_pk>[0-9]+)/editar/$', views.EditarVenta.as_view(), name='editar_venta'),
    url(r'^(?P<venta_pk>[0-9]+)/eliminar/$', views.EliminarVenta.as_view(), name='eliminar_venta'),
]

veterinaria1/urls.py
# -*- coding: utf-8 -*-
"""veterinaria URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, patterns, url, i18n
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django_apps.home import views
import ajax_select

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('django_apps.home.urls')),
    url(r'^persona/', include('django_apps.persona.urls')),
    url(r'^inventario/', include('django_apps.inventario.urls')),
    url(r'^compras/', include('django_apps.compras.urls')),
    url(r'^ventas/', include('django_apps.ventas.urls')),
    url(r'^clinica/', include('django_apps.clinica.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ajax-select/', include('ajax_select.urls')),
    # url(r'^rosetta/', include('rosetta.urls')),
    url(r'^$', views.setlanguage, name='setlanguage'),

    #Gestion de Usuarios Empleados

    # url(r'^logout/$', views.logout_view, name='logout_empleado'),

    ## Gestion de Perfiles de Usuarios Empleados
    # url(r'^empleado/(?P<pk>[0-9]+)/$', views.DetailPerfilEmpleado.as_view(),
    #     name='detalle_perfil_empleado'),
    # url(r'^empleado/(?P<pk>[0-9]+)/editar/$', views.ActualizarPerfilEmpleado.as_view(),
    #     name='editar_perfil_empleado'),

]
handler400 = 'django_apps.home.views.bad_request'
handler403 = 'django_apps.home.views.permission_denied'
handler404 = 'django_apps.home.views.page_not_found'
handler500 = 'django_apps.home.views.server_error'

urlpatterns += i18n_patterns(
    url(r'^$', views.setlanguage, name='setlanguage'),
    # url(r'^$', home, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^persona/', include('django_apps.persona.urls')),
    url(r'^inventario/', include('django_apps.inventario.urls')),
    url(r'^compras/', include('django_apps.compras.urls')),
    url(r'^ventas/', include('django_apps.ventas.urls')),
    url(r'^clinica/', include('django_apps.clinica.urls')),
    # url(r'^', include('django_apps.home.urls')),
    # url(r'^ajax-select/', include('ajax_select.urls')),
)


# handler404 = 'views.Page_not_Found'

if settings.DEBUG:
    # urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_apps/clinica/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django_apps.persona.models import Cliente
from django.forms.models import BaseInlineFormSet
from django.forms.models import inlineformset_factory
from .models import Mascota, Vacuna, Desparacitante, EstadoMascota

class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota
        fields = ['propietario','nombre','raza','color','especie','edad',
                  'peso','descripcion','avatar','ambiental','alimento','bano']

    def __init__(self, *args, **kwargs):
        super(MascotaForm, self).__init__(*args, **kwargs)
        self.fields['propietario'].widget.attrs.update({'class' : 'chosen'})
        self.fields['nombre'].widget.attrs.update({'class' : 'form-control'})
        self.fields['raza'].widget.attrs.update({'class' : 'form-control'})
        self.fields['color'].widget.attrs.update({'class' : 'form-control'})
        self.fields['especie'].widget.attrs.update({'class' : 'form-control'})
        self.fields['edad'].widget.attrs.update({'class' : 'form-control input-mask','placeholder':'eg: 000.000.000.000.000,00'})
        self.fields['peso'].widget.attrs.update({'class' : 'form-control input-mask','placeholder':'eg: 000.000.000.000.000,00'})
        self.fields['descripcion'].widget.attrs.update({'class' : 'form-control','rows':'4','placeholder':'Breve descripción de la Mascota'})
        self.fields['ambiental'].widget.attrs.update({'class' : 'form-control','rows':'4','placeholder':'¿Desde cuando está enfermo el animal?\n¿Si esta enfermedad ha sido tratada o no?'})
        self.fields['alimento'].widget.attrs.update({'class' : 'form-control','rows':'6','placeholder':'¿Qué tipo de dieta se le suministra?\nCasera o fabricado (seca, húmeda,semi seca)\nMarca de la comida,\nTipo de alimentación(libre elección o comida individual)'})
        self.fields['bano'].widget.attrs.update({'class' : 'form-control','rows':'4','placeholder':'¿Cuantas veces por mes se le baña al animal?'})

class VacunaForm(forms.ModelForm):
    class Meta:
        model = Vacuna
        fields = ['vacuna','fecha']

    def __init__(self, *args, **kwargs):
        super(VacunaForm, self).__init__(*args, **kwargs)
        self.fields['vacuna'].widget.attrs.update({'class' : 'form-control vacuna'})
        self.fields['fecha'].widget.attrs.update({'class' : 'form-control input-mask','data-mask':'00/00/0000','placeholder':'eg: 23/05/2014','maxlength':'10','autocomplete':'off'})

class DesparacitanteForm(forms.ModelForm):
    class Meta:
        model = Desparacitante
        fields = ['producto','fecha']

    def __init__(self, *args, **kwargs):
        super(DesparacitanteForm, self).__init__(*args, **kwargs)
        self.fields['producto'].widget.attrs.update({'class' : 'form-control despar'})
        self.fields['fecha'].widget.attrs.update({'class' : 'form-control input-mask','data-mask':'00/00/0000','placeholder':'eg: 23/05/2014','maxlength':'10','autocomplete':'off'})

class EstadoMascotaForm(forms.ModelForm):
    class Meta:
        model = EstadoMascota
        fields = ['mascota','motivo','fr','fc','fp','t','exampiel','examucvis',
                  'gangpal','apetito','sed','defecac','miccion']

    def __init__(self, *args, **kwargs):
        super(EstadoMascotaForm, self).__init__(*args, **kwargs)
        self.fields['mascota'].widget.attrs.update({'class' : 'chosen'})
        self.fields['motivo'].widget.attrs.update({'class' : 'form-control'})
        self.fields['fr'].widget.attrs.update({'class' : 'form-control'})
        self.fields['fc'].widget.attrs.update({'class' : 'form-control'})
        self.fields['fp'].widget.attrs.update({'class' : 'form-control'})
        self.fields['t'].widget.attrs.update({'class' : 'form-control'})
        self.fields['exampiel'].widget.attrs.update({'class' : 'form-control'})
        self.fields['examucvis'].widget.attrs.update({'class' : 'form-control'})
        self.fields['gangpal'].widget.attrs.update({'class' : 'form-control'})
        self.fields['apetito'].widget.attrs.update({'class' : 'form-control'})
        self.fields['sed'].widget.attrs.update({'class' : 'form-control'})
        self.fields['defecac'].widget.attrs.update({'class' : 'form-control'})
        self.fields['miccion'].widget.attrs.update({'class' : 'form-control'})

class RequiredBaseInlineFormSet(BaseInlineFormSet):
    def clean(self):
        self.validate_unique()
        if any(self.errors):
            return
        if not self.forms[0].has_changed():
            raise forms.ValidationError("At least one %s is required" % self.model._meta.verbose_name)

VacunaFormSet = inlineformset_factory(Mascota, Vacuna, form=VacunaForm,formset=RequiredBaseInlineFormSet,extra=1,max_num=10)
DesparacitanteFormSet = inlineformset_factory(Mascota, Desparacitante, form=DesparacitanteForm,formset=RequiredBaseInlineFormSet,extra=1,max_num=10)

templates/clinica/confirmar_eliminar_estado_mascota.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<style type="text/css">
    #eliminar{
        width:60%;
        margin: 0 auto;
    }
    #borrado{
        text-align: center;
    }
</style>
{% endblock extrahead %}
{% block content %}
<div class="card-header">
    <h2 id="borrado">Borrar Estado de la Mascota {{object.mascota.nombre}}</h2>
</div>   
<div class="card-body card-padding">    
    <div id="eliminar">
        <div class="bs-item z-depth-5">
            <form method="post">{% csrf_token %} 
                <p class="f-500 c-black m-b-15"> ¿Realmente quieres borrar la ficha {{object.fichaseg}} de la mascota <strong>{{object.mascota.nombre }} </strong>?</p> 
                <button type="submit" class="btn btn-primary btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-check"></i></button>
                <a href="{% url 'clinica:historial_mascota' object.mascota.propietario.slug object.mascota.slug %}" class="btn bgm-deeporange btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-close"></i></a>
            </form> 
        </div>
    </div>
{% endblock content %} 

templates/clinica/detalle_estado_mascota.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% block extrahead %}
<link href="{% static 'css/list.css' %}" rel="stylesheet">
<style type="text/css">
    #img{
        width:40%;
        margin: 0 auto;
    }
    .pmo-contact{
        width:70%;
        margin: 0 auto;
        padding: 2em;
        border-radius: 20px;
        border: 1px solid #00B0FF;
    }
    .card-header {
        text-align: center;
    }
</style>
{% endblock extrahead %}
{% block content %}
<div class="card-header ch-alt bgm-orange ">
    <h2>Ficha N° {{object.fichaseg}} de la Mascota
        {{object.mascota.nombre}}<small>{{object.motivo}}</small>
    </h2>
</div>
<div class="card-body card-padding">
    <a class="pmo-map"id="img" href="">
        <img src="{{object.mascota.avatar.url}}" >
    </a>
    <div class="pmo-contact">
        <ol id="list" class="rounded-list">
            <li><a href=""><strong>Constantes Clínicas</strong></a> 
                <ol> 
                    <li><a  href=""><strong>FR: </strong>{{object.fr}}</a></li> 
                    <li><a  href=""><strong>FC: </strong>{{object.fc}}</a></li> 
                    <li><a  href=""><strong>FP: </strong>{{object.fp}}</a></li>
                    <li><a  href=""><strong>T: </strong>{{object.t}}</a></li>  
                </ol> 
            </li>
            <li><a href=""><strong>Examen de Piel: </strong>{{object.exampiel}}</a></li>
            <li><a href=""><strong>Examen  de mucosas Visibles: </strong>{{object.examucvis}}</a></li>
            <li><a href=""><strong>Ganglios Palpables: </strong>{{object.gangpal}}</a></li>
            <li><a href=""><strong>Grandes Funciones</strong></a> 
                <ol> 
                    <li><a  href=""><strong>Apetito: </strong>{{object.apetito}}</a></li> 
                    <li><a  href=""><strong>Sed: </strong>{{object.sed}}</a></li> 
                    <li><a  href=""><strong>Defecación: </strong>{{object.defecac}}</a></li> 
                    <li><a  href=""><strong>Micción: </strong>{{object.miccion}}</a></li> 
                </ol> 
            </li>                         
        </ol> 
    </div>
    <a href="{% url 'clinica:nuevo_estado_mascota' object.mascota.propietario.slug object.mascota.slug %}" class="btn btn-warning btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-plus"></i></a> &nbsp;
    <a href="{% url 'clinica:historial_mascota' object.mascota.propietario.slug object.mascota.slug %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-mail-reply"></i></a>
</div>
{% endblock content %}

templates/clinica/mascotas.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<link href="{% static 'css/jquery.bootgrid.min.css' %}" rel="stylesheet">
<style type="text/css">
    #buscar{
        width:36%;
    }
    #buscar input{
        width:25em;;
    }
    .fg-line, #btn{
        position:relative;
        display:inline-block;
    }
    .pag2{
        width:30%;
        padding:0.5em 1em 0.5em 1em;
        text-align:center;
        border: 1px solid #cdcdcd;
    }
    #fast{
        margin-left:30em;    
    }
    #mascota {
        font-size:2em;
        text-align:center;
    }
    #btn{
        margin-left:1em;
    }
    .list{
        width:50%;
        border-radius: 20%;        
    }
    #notfound {
        width:100%;
        margin: 0 auto;
        color: #fff;
        text-shadow: 1px 0px 3px #00B0FF;
        padding: 3em;
        border-radius: 12px;
        background: #FFF9C4;
        text-align: center;
    }
</style>
{% endblock extrahead %}
{% block content %}
<div class="card-header ch-alt bgm-cyan">
    {% if listar_mascotas %}
    {% for i in listar_mascotas %}
    {% if i.propietario.slug in cliente.slug %}
    <h2 id="mascota">Mascotas de {{cliente.nombre}} {{cliente.ap_pater}} {{cliente.ap_mater}}</h2>
    {% endif %}
    {% empty %}
    <h2 id="mascota">El cliente No tiene Mascotas</h2>
    {% endfor %}
    {% endif %}
</div>   
<div class="card-body card-padding">   
    <div class="btn-demo">
        <table id="data-table" class="table table-striped table-vmiddle">
            {% if listar_mascotas %}
            {% for i in listar_mascotas %}
            {% if i.propietario.slug in cliente.slug %}
            <div class="ms-search hidden-xs">
                <form action="{% url 'clinica:buscar_mascota' cliente.slug %}" method="GET">
                    <div class="row">
                        <div id="buscar" class="col-sm-4">
                            <div class="input-group">
                                <i type="submit" class="zmdi zmdi-search"></i>
                                <input type="text" name="q" value="{{ query|escape }}" class="form-control" placeholder="Search...">
                            </div>
                        </div>
                        <div id="buscar"class="col-sm-4">
                            <div class="input-group">
                                <button type="submit" id="btn" class="btn btn-info">Enviar <i class="zmdi zmdi-mail-send"></i></button>
                                <a href="{% url 'clinica:propietarios' %}"  type="submit" id="btn" class="btn  btn-default">Volver <i class="zmdi zmdi-mail-reply"></i></a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <thead>
                <tr>
                    <th data-column-id="id" data-type="numeric">ID</th> 
                    <th data-column-id="sender">Mascota</th> 
                    <th data-column-id="names" data-order="desc">N° Ficha</th> 
                    <th data-column-slug="commands" data-formatter="commands" data-sortable="false">Acciones</th>
                </tr>  
                {% endif %}
                {% empty %}
                <h2 id="notfound">No hay Mascotas</h2>
                {% endfor %}
                {% endif %}
            </thead>
            <tbody>
                {% for i in listar_mascotas %}
                {% if i.propietario.slug in cliente.slug %}
                <tr>
                    <td>{{i.id}}</td> 
                    <td>{{i.nombre}}</td>                     
                    <td>{{i.ficha}}</td> 
                    <td> 
                        {% if historial_mascota %}
                        {% for j in historial_mascota|slice:":1"%}
                        {% if j.mascota.nombre in i.nombre %}
                        <a href="{% url 'clinica:historial_mascota' i.propietario.slug  i.slug %}"class="btn btn-default btn-icon" >
                            <img src="{% static 'img/house.png' %}" class="list">
                        </a>                        
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                        <a href="{% url 'clinica:nuevo_estado_mascota' i.propietario.slug  i.slug %}"class="btn btn-default btn-icon" >
                            <img src="{% static 'img/checkeo.png'%}" class="list" >
                        </a>
                        <a href="{% url 'clinica:editar_mascota' i.propietario.slug  i.slug %}"class="btn btn-primary btn-icon" ><i class="zmdi zmdi-edit"></i></a>
                        <a href="{% url 'clinica:detalle_mascota' i.propietario.slug i.slug %}" class="btn btn-info btn-icon"><i class="zmdi zmdi-assignment"></i></a> 
                        <a href="{% url 'clinica:eliminar_mascota' i.propietario.slug i.slug %}" class="btn bgm-deeporange btn-icon"><i class="zmdi zmdi-delete"></i><a>
                    </td>
                </tr>
                {% else %}
                {% endif %}
                {% endfor %}
               
            </tbody>
        </table>
        {% if listar_mascotas %}
        {% for i in listar_mascotas|slice:":1" %}
        {% if i.propietario.slug in cliente.slug %}
        <a href="{% url 'clinica:agregar_mascota' cliente.slug %}" class="btn btn-primary btn-block">Agregar Nueva Mascota</a>
        {% else %}
        <a href="{% url 'clinica:agregar_mascota' cliente.slug %}" class="btn btn-primary btn-block">Agregar Nueva Mascota</a>
        <a href="{% url 'clinica:propietarios' %}" class="btn bgm-amber btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-arrow-left"></i></a>
        {% endif %}
        {% endfor %}
        {% else %}
        {% endif %}
    </div>
    {% if is_paginated %}
    <div class="row">
    <div id="fast" class="col-sm-6">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}"><i class="zmdi zmdi-fast-rewind "></i></a></li>
            {% else %}
            <li class="disabled"><a href="#!"><i class="zmdi zmdi-fast-rewind "></i></a></li>
            {% endif %}
            <li class="active"><a href="">{{page_obj.number}}</a></li>
            {% if page_obj.has_next %}
            <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}"><i class="zmdi zmdi-fast-forward"></i></a></li>
            {% else %}
            <li class="disabled"><a href="#!"><i class="zmdi zmdi-fast-forward"></i></a></li>
            {% endif %}
        </ul>
    </div>
    <div id="fast"class="col-sm-6 infoBar">
        <div class="pag2">
            Page {{ page_obj.number }} of {{ paginator.num_pages }}.
        </div>
    </div>
    </div>
    {% endif %}
</div>
{% endblock content %}
{% block script %}
<script src="{% static 'js/jquery.bootgrid.updated.min.js' %}"></script>
 <script type="text/javascript">
            $(document).ready(function(){
                //Basic Example
                $("#data-table-basic").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                });

                //Selection
                $("#data-table-selection").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                    selection: true,
                    multiSelect: true,
                    rowSelect: true,
                    keepSelection: true
                });

                //Command Buttons
                $("#data-table-command").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                });
            });
        </script>
{% endblock script %}    