django_apps/compras/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name = 'compras'

urlpatterns = [
    url(r'^$', views.ListaCompras.as_view(), name='listar_compras'),
    url(r'^search-compra/$', views.search_compra, name="buscar_compra"),
    url(r'^almacen/$', views.Almacen.as_view(), name='almacen'),
    url(r'^(?P<proveedor_slug>[\w-]+)/nueva-compra/$', views.NuevaCompraProveedor.as_view(), name='nueva_compra_proveedor'),
    url(r'^nueva-compra/$', views.NuevaCompra.as_view(), name='nueva_compra'),
    url(r'^(?P<compra_pk>[0-9]+)/$', views.DetalleCompra.as_view(), name='detalle_compra'),
    url(r'^(?P<compra_pk>[0-9]+)/editar/$', views.EditarCompra.as_view(), name='editar_compra'),
    url(r'^(?P<compra_pk>[0-9]+)/eliminar/$', views.EliminarCompra.as_view(), name='eliminar_compra'),
]

django_apps/ventas/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'ventas'

urlpatterns = [
    url(r'^(?P<venta_pk>[0-9]+)/editar-venta/$', views.UpdateVenta, name='update_venta'),
    url(r'^$', views.ListaVentas.as_view(), name='listar_ventas'),
    url(r'^search-venta/$', views.search_venta, name='buscar_venta'),
    # url(r'^nuevo/$', views.NuevaVenta, name='nueva_venta'),
    url(r'^nueva-venta/$', views.CreateVenta, name='venta_nueva'),
    #
    url(r'^(?P<venta_pk>[0-9]+)/$', views.DetalleVenta.as_view(), name='detalle_venta'),
    #PDF Venta
    url(r'^(?P<venta_pk>[0-9]+)/venta-pdf/$', views.VentaPDF.as_view(), name='pdf_venta'),
    # url(r'^(?P<venta_pk>[0-9]+)/editar/$', views.EditarVenta.as_view(), name='editar_venta'),
    url(r'^(?P<venta_pk>[0-9]+)/eliminar/$', views.EliminarVenta.as_view(), name='eliminar_venta'),
]

veterinaria1/urls.py
# -*- coding: utf-8 -*-
"""veterinaria URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, patterns, url, i18n
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django_apps.home import views
import ajax_select

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('django_apps.home.urls')),
    url(r'^persona/', include('django_apps.persona.urls')),
    url(r'^inventario/', include('django_apps.inventario.urls')),
    url(r'^compras/', include('django_apps.compras.urls')),
    url(r'^ventas/', include('django_apps.ventas.urls')),
    url(r'^clinica/', include('django_apps.clinica.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ajax-select/', include('ajax_select.urls')),
    # url(r'^rosetta/', include('rosetta.urls')),
    url(r'^$', views.setlanguage, name='setlanguage'),

    #Gestion de Usuarios Empleados

    # url(r'^logout/$', views.logout_view, name='logout_empleado'),

    ## Gestion de Perfiles de Usuarios Empleados
    # url(r'^empleado/(?P<pk>[0-9]+)/$', views.DetailPerfilEmpleado.as_view(),
    #     name='detalle_perfil_empleado'),
    # url(r'^empleado/(?P<pk>[0-9]+)/editar/$', views.ActualizarPerfilEmpleado.as_view(),
    #     name='editar_perfil_empleado'),

]
handler400 = 'django_apps.home.views.bad_request'
handler403 = 'django_apps.home.views.permission_denied'
handler404 = 'django_apps.home.views.page_not_found'
handler500 = 'django_apps.home.views.server_error'

urlpatterns += i18n_patterns(
    url(r'^$', views.setlanguage, name='setlanguage'),
    # url(r'^$', home, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^persona/', include('django_apps.persona.urls')),
    url(r'^inventario/', include('django_apps.inventario.urls')),
    url(r'^compras/', include('django_apps.compras.urls')),
    url(r'^ventas/', include('django_apps.ventas.urls')),
    url(r'^clinica/', include('django_apps.clinica.urls')),
    # url(r'^', include('django_apps.home.urls')),
    # url(r'^ajax-select/', include('ajax_select.urls')),
)


# handler404 = 'views.Page_not_Found'

if settings.DEBUG:
    # urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_apps/ventas/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.forms.models import inlineformset_factory
from .models import OrdenVenta, CarritoVenta

class OrdenVentaForm(forms.ModelForm):
    class Meta:
        model = OrdenVenta
        fields = ['cliente']

    def __init__(self, *args, **kwargs):
        super(OrdenVentaForm, self).__init__(*args, **kwargs)
        self.fields['cliente'].widget.attrs.update({'class' : 'chosen'})
        # cliente = self.instance.cliente
        # self.fields['cliente'].queryset = Cliente.objects.get(slug = cliente.slug)

class CarritoVentaForm(forms.ModelForm):
    class Meta:
        model = CarritoVenta
        fields = ['producto','cantidad']

    def __init__(self, *args, **kwargs):
        super(CarritoVentaForm, self).__init__(*args, **kwargs)
        self.fields['producto'].widget.attrs.update({'class' : 'chosen'})
        self.fields['cantidad'].widget.attrs.update({'class' : 'form-control input-mask','placeholder':'eg: 000.000.000.000.000,00'})

CarritoVentaFormset = inlineformset_factory(OrdenVenta,CarritoVenta,
                                            form=CarritoVentaForm,extra=1, max_num=10)

django_apps/ventas/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.template.context_processors import csrf
from django.db.models import Q
from django.template import RequestContext
from django.conf import settings
from django.forms.formsets import formset_factory, BaseFormSet
from django.http import HttpResponse, HttpResponseRedirect, Http404
from wkhtmltopdf.views import PDFTemplateResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import *
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.messages.views import SuccessMessageMixin
from django_apps.home.views import LoginRequiredMixin
from django.forms.models import BaseInlineFormSet
from django.forms.models import inlineformset_factory

from django.contrib import messages
from .models import OrdenVenta, CarritoVenta
from .forms import OrdenVentaForm, CarritoVentaForm, CarritoVentaFormset

@login_required(login_url='home:login_empleado')
def search_venta(request):
    query = request.GET.get('q', '')
    if query:
        qset = (
            Q(id__icontains=query)|
            Q(codigo__icontains=query)|
            Q(cliente__nombre__icontains=query)|
            Q(cliente__ap_pater__icontains=query)|
            Q(cliente__ap_mater__icontains=query)
        )
        results = OrdenVenta.objects.filter(qset).distinct()
    else:
        results = []
    return render_to_response("ventas/search_venta.html", {
        "results": results,
        "query": query
    })

class RequiredBaseInlineFormSet(BaseInlineFormSet):
    def clean(self):
        self.validate_unique()
        if any(self.errors):
            return
        if not self.forms[0].has_changed():
            raise forms.ValidationError("At least one %s is required" % self.model._meta.verbose_name)

@login_required(login_url='home:login_empleado')
def CreateVenta(request):
    venta_form = OrdenVentaForm(request.POST or None)
    CarritoFormSet = inlineformset_factory(OrdenVenta, CarritoVenta, form=CarritoVentaForm,formset=RequiredBaseInlineFormSet, max_num=10, extra=1)
    carrito_formset = CarritoFormSet(request.POST or None, prefix='carrito')
    if venta_form.is_valid() and carrito_formset.is_valid():
        venta = venta_form.save()
        carrito = carrito_formset.save(commit=False)
        for producto in carrito:
            producto.venta = venta
            producto.save()
        messages.add_message(request, messages.INFO, 'Venta efectuada correctamente')
        return HttpResponseRedirect(venta.get_absolute_url())
    return render_to_response(
        'ventas/venta_form.html', {
            'form': venta_form,
            'formset':carrito_formset,
        }, context_instance = RequestContext(request)
    )


@login_required(login_url='home:login_empleado')
def UpdateVenta(request, venta_pk=None):
    # if not request.user.is_staff or not request.user.is_superuser:
    #     raise Http404
    instance = OrdenVenta.objects.get(pk=venta_pk)
    venta_form = OrdenVentaForm(request.POST or None, instance=instance)
    CarritoFormSet = inlineformset_factory(OrdenVenta, CarritoVenta, form=CarritoVentaForm,formset=RequiredBaseInlineFormSet, max_num=10, extra=1)
    carrito_formset = CarritoFormSet(request.POST or None, prefix='carrito', instance=instance)
    if venta_form.is_valid() and carrito_formset.is_valid():
        venta = venta_form.save()
        carrito = carrito_formset.save(commit=False)
        for producto in carrito:
            producto.venta = venta
            producto.save()
        messages.add_message(request, messages.INFO, 'Venta editada correctamente')
        return HttpResponseRedirect(venta.get_absolute_url())
    return render_to_response(
        'ventas/venta_form.html', {
            'form': venta_form,
            'formset':carrito_formset,
        }, context_instance = RequestContext(request)
    )

class ListaVentas(LoginRequiredMixin,ListView):
    model = OrdenVenta
    paginate_by = 10
    context_object_name = 'listar_ventas'
    template_name = 'ventas/ventas.html'

class DetalleVenta(LoginRequiredMixin,DetailView):
    model = OrdenVenta
    template_name = 'ventas/detalle_venta.html'
    pk_url_kwarg = 'venta_pk'

    def get_context_data(self, **kwargs):
        context = super(DetalleVenta, self).get_context_data(**kwargs)
        # context['productos'] = CarritoVenta.objects.get(pk=self.kwargs.get('venta_pk',None))
        context['productos'] = CarritoVenta.objects.filter(venta_id=self.object.id)
        a = CarritoVenta.objects.all().values()
        t = 0
        for j in range(len(a)):
            if self.object.id == a[j].get('venta_id'):
                t += float(a[j].get('total'))
        context['total_venta'] = t
        return context

class VentaPDF(DetailView):
    model = OrdenVenta
    pk_url_kwarg = 'venta_pk'
    template='ventas/venta_pdf.html'
    context= {'title': 'Detalle de Venta'}


    def get(self, request, *args, **kwargs):
        self.context['venta'] = self.get_object()
        self.context['productos'] = CarritoVenta.objects.filter(venta_id=self.get_object().id)
        a = CarritoVenta.objects.all().values()
        t = 0
        for j in range(len(a)):
            if self.get_object().id == a[j].get('venta_id'):
                t += float(a[j].get('total'))
        self.context['total_venta'] = t

        response=PDFTemplateResponse(request=request,
                                     template=self.template,
                                     # filename ="venta.pdf",
                                     context=self.context,
                                     show_content_in_browser=False,
                                     # cmd_options=settings.WKHTMLTOPDF_CMD_OPTIONS,
                                     )
        return response

class EliminarVenta(LoginRequiredMixin,SuccessMessageMixin,DeleteView):
    model = OrdenVenta
    pk_url_kwarg = 'venta_pk'
    success_url = reverse_lazy('ventas:listar_ventas')
    success_message = 'La venta se eliminó con éxito'
    template_name = 'ventas/confirmar_eliminar_venta.html'

# class NuevaVenta(LoginRequiredMixin,SuccessMessageMixin,CreateView):
#     model = OrdenVenta
#     form_class = OrdenVentaForm
#     success_message = 'La venta se realizó correctamente'
#     pk_url_kwarg = 'venta_pk'
#     template_name = 'ventas/nueva_venta.html'

#     def get(self, request, *args, **kwargs):
#         self.object = None
#         form_class = self.get_form_class()
#         form = self.get_form(form_class)
#         carrito_form = CarritoVentaFormset(instance = self.object)
#         return self.render_to_response(self.get_context_data(form = form, carrito_form = carrito_form))

#     def post(self, request, *args, **kwargs):
#         self.object = None
#         form_class = self.get_form_class()
#         form = self.get_form(form_class)
#         carrito_form = CarritoVentaFormset(self.request.POST, prefix='carrito')
#         if (form.is_valid() and carrito_form.is_valid()):
#             return self.form_valid(form, carrito_form)
#         else:
#             return self.form_invalid(form, carrito_form)

#     def form_valid(self, form, carrito_form):
#         self.object = form.save()
#         carrito_form.instance = self.object
#         carrito_form.save()
#         return HttpResponseRedirect(self.get_success_url())

#     def form_invalid(self, form, carrito_form):
#         return self.render_to_response(
#             self.get_context_data(form=form,
#                                   carrito_form=carrito_form)
#         )

# class EditarVenta(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
#     template_name = 'ventas/nueva_venta.html'
#     model = OrdenVenta
#     success_message = 'La venta se editó correctamente'
#     pk_url_kwarg = 'venta_pk'
#     form_class = OrdenVentaForm

#     # def get_context_data(self, **kwargs):
#     #     context = super(EditarVenta, self).get_context_data(**kwargs)
#     #     if self.request.POST:
#     #         context['form'] = OrdenVentaForm(self.request.POST, instance=self.object)
#     #         context['carrito_form'] = CarritoVentaFormset(self.request.POST, instance=self.object)
#     #     else:
#     #         context['form'] = RecipeForm(instance=self.object)
#     #         context['carrito_form'] = CarritoVentaFormset(instance=self.object)
#     #     return context
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         form_class = self.get_form_class()
#         form = self.get_form(form_class)
#         carrito_form = CarritoVentaFormset(instance = self.object)
#         return self.render_to_response(self.get_context_data(form = form,
#                                                              carrito_form = carrito_form))

#     def post(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         form_class = self.get_form_class()
#         form = self.get_form(form_class)
#         carrito_form = CarritoVentaFormset(self.request.POST, prefix='carrito')
#         if (form.is_valid() and carrito_form.is_valid()):
#             return self.form_valid(form, carrito_form)
#         else:
#             return self.form_invalid(form, carrito_form)

#     def form_valid(self, form, carrito_form):
#         self.object = form.save()
#         carrito_form.instance = self.object
#         carrito_form.save()
#         return HttpResponseRedirect(self.get_success_url())

#     def form_invalid(self, form, carrito_form):
#         return self.render_to_response(
#             self.get_context_data(form=form,
#                                   carrito_form=carrito_form)
#         )

templates/ventas/confirmar_eliminar_venta.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<style type="text/css">
    #eliminar{
        width:50%;
        margin: 0 auto;
    }
    #borrado{
        text-align: center;
    }
</style>
{% endblock extrahead %}
{% block content %}
<div class="card-header">
    <h2 id="borrado">Borrado de Venta</h2>
</div>   
<div class="card-body card-padding">    
    <div id="eliminar">
        <div class="bs-item z-depth-5">
            <form method="post">{% csrf_token %} 
                <p class="f-500 c-black m-b-15"> ¿Realmente quieres borrarla venta que se hizo <strong>{{object.cliente.nombre }} </strong>"?</p> 
                <button type="submit" class="btn btn-primary btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-check"></i></button>
                <button class="btn bgm-deeporange btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-close"></i></button>
            </form> 
        </div>
    </div>
{% endblock content %}    

templates/ventas/search_venta.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% load i18n %}
{% block titulo %}
Search{% if query %} Resultados{% endif %}
{% endblock titulo %}
{% block extrahead %}
<link href="{% static 'css/jquery.bootgrid.min.css' %}" rel="stylesheet">
<style type="text/css">
    #buscar{
        width:36%;
    }
    #buscar input{
        width:25em;;
    }
    .fg-line{
    }
    .fg-line, #btn{
        position:relative;
        display:inline-block;
    }
    #btn{
        margin-right:1em;
    }
</style>
{% endblock extrahead %}
{% block content %}
<div class="card-header">
    <h2>Resultados de Búsqueda de Compra</h2>
</div>   
<div class="card-body card-padding">   
    <div class="btn-demo">
        <table id="data-table" class="table table-striped table-vmiddle">
            <div class="ms-search hidden-xs">
                <form action="{% url 'ventas:buscar_venta' %}" method="GET">
                    <div class="row">
                        <div id="buscar" class="col-sm-4">
                            <div class="input-group">
                                <i type="submit" class="zmdi zmdi-search"></i>
                                <input type="text" name="q" value="{{ query|escape }}" class="form-control" placeholder="Search...">
                            </div>
                        </div>
                        <div id="buscar"class="col-sm-4">
                            <div class="input-group">
                                <button type="submit" id="btn" class="btn btn-info">Enviar <i class="zmdi zmdi-mail-send"></i></button>
                                <a href="{% url 'ventas:listar_ventas' %}"  type="submit" id="btn" class="btn  btn-default">Volver <i class="zmdi zmdi-mail-reply"></i></a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            {% if query %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                Resultados de búsqueda Ventas de la Empresa Only Pets S.R.L
            </div>
            {% if results %}
            <thead>
                <tr>
                    <th data-column-id="id" data-type="numeric">ID</th> 
                    <th data-column-id="sender">Cliente</th> 
                    <th data-column-id="codigo" data-order="desc">Código</th> 
                    <th data-column-slug="commands" data-formatter="commands" data-sortable="false">Acciones</th>
                </tr>  
            </thead>
            <tbody>
                {% for i in results %}
                <tr>
                    <td>{{i.id}}</td> 
                    <td>{{i.cliente.nombre}}</td> 
                    <td>{{i.codigo}}</td> 
                    <td> 
                        <a href="{% url 'ventas:update_venta' i.pk %}"class="btn btn-primary btn-icon" ><i class="zmdi zmdi-edit"></i></a>
                        <a href="{% url 'ventas:detalle_venta' i.pk %}" class="btn btn-info btn-icon"><i class="zmdi zmdi-assignment"></i></a> 
                        <a href="{% url 'ventas:eliminar_venta' i.pk %}" class="btn bgm-deeporange btn-icon"><i class="zmdi zmdi-delete"></i><a>
                    </td> 
                </tr>
                {% endfor %}
                {% else %}
                 <div class="col-sm-3">
                    <p class="f-500 c-black m-b-20">Lo sentimos no hay compras,
                        si desea agregar ...<a href="{% url 'compras:venta_nueva' %}" class="btn btn-info" id="sa-warning">Click me</a>
                </div> 
            {% endif %}
            {% endif %}
            </tbody>
        </table>
        <a href="{% url 'ventas:venta_nueva' %}" class="btn btn-primary btn-block">Agregar Nuevo Venta</a>
    </div>
</div>
{% endblock content %}
{% block script %}
<script src="{% static 'js/jquery.bootgrid.updated.min.js' %}"></script>
 <script type="text/javascript">
            $(document).ready(function(){
                //Basic Example
                $("#data-table-basic").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                });

                //Selection
                $("#data-table-selection").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                    selection: true,
                    multiSelect: true,
                    rowSelect: true,
                    keepSelection: true
                });

                //Command Buttons
                $("#data-table-command").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },

                });
            });
        </script>
{% endblock script %}   

templates/ventas/ventas.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<link href="{% static 'css/jquery.bootgrid.min.css' %}" rel="stylesheet">
<style type="text/css">
    #buscar{
        width:36%;
    }
    #buscar input{
        width:25em;;
    }
    .fg-line, #btn{
        position:relative;
        display:inline-block;
    }
    .pag2{
        width:30%;
        padding:0.5em 1em 0.5em 1em;
        text-align:center;
        border: 1px solid #cdcdcd;
    }
    #fast{
        margin-left:30em;    
    }
    #venta {
        text-align:center;
        font-size:2em;
    }
</style>
{% endblock extrahead %}
{% block content %}
<div class="card-header ch-alt bgm-cyan">
     <h2 id='venta'>Ventas</h2>
</div>
<div class="card-body card-padding">   
    <div class="btn-demo">
        <table id="data-table" class="table table-striped table-vmiddle">
            {% if listar_ventas %}
            <div class="ms-search hidden-xs">
                <form action="{% url 'ventas:buscar_venta' %}" method="GET">
                    <div class="row">
                        <div id="buscar" class="col-sm-4">
                            <div class="input-group">
                                <i type="submit" class="zmdi zmdi-search"></i>
                                <input type="text" name="q" value="{{ query|escape }}" class="form-control" placeholder="Search...">
                            </div>
                        </div>
                        <div id="buscar"class="col-sm-4">
                            <div class="input-group">
                                <button type="submit" id="btn" class="btn btn-info">Enviar <i class="zmdi zmdi-mail-send"></i></button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            {% endif %}
            <thead>
                {% if listar_ventas %}
                <tr>
                    <th data-column-id="id" data-type="numeric">ID</th> 
                    <th data-column-id="sender">Cliente</th> 
                    <th data-column-id="sender">Código</th> 
                    <th data-column-slug="commands" data-formatter="commands" data-sortable="false">Acciones</th>
                </tr>  
                {% endif %}
            </thead>
            <tbody>
                {% for i in listar_ventas %}
                <tr>
                    <td>{{i.id}}</td> 
                    <td>{{i.cliente.nombre}}</td> 
                    <td>{{i.codigo}}</td> 
                    <td> 
                        <a href="{% url 'ventas:update_venta' i.pk %}"class="btn btn-primary btn-icon" ><i class="zmdi zmdi-edit"></i></a>
                        <a href="{% url 'ventas:detalle_venta' i.pk %}" class="btn btn-info btn-icon"><i class="zmdi zmdi-assignment"></i></a> 
                        <a href="{% url 'ventas:eliminar_venta' i.pk %}" class="btn bgm-deeporange btn-icon"><i class="zmdi zmdi-delete"></i><a>
                    </td>
                </tr>
                {% endfor %}
               
            </tbody>
        </table>
        <a href="{% url 'ventas:venta_nueva' %}" class="btn btn-primary btn-block">Agregar Nuevo Venta</a>
    </div>
    {% if is_paginated %}
    <div class="row">
    <div id="fast" class="col-sm-6">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}"><i class="zmdi zmdi-fast-rewind "></i></a></li>
            {% else %}
            <li class="disabled"><a href="#!"><i class="zmdi zmdi-fast-rewind "></i></a></li>
            {% endif %}
            <li class="active"><a href="">{{page_obj.number}}</a></li>
            {% if page_obj.has_next %}
            <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}"><i class="zmdi zmdi-fast-forward"></i></a></li>
            {% else %}
            <li class="disabled"><a href="#!"><i class="zmdi zmdi-fast-forward"></i></a></li>
            {% endif %}
        </ul>
    </div>
    <div id="fast"class="col-sm-6 infoBar">
        <div class="pag2">
            Page {{ page_obj.number }} of {{ paginator.num_pages }}.
        </div>
    </div>
    </div>
    {% endif %}
</div>
{% endblock content %}
{% block script %}
<script src="{% static 'js/jquery.bootgrid.updated.min.js' %}"></script>
 <script type="text/javascript">
            $(document).ready(function(){
                //Basic Example
                $("#data-table-basic").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                });

                //Selection
                $("#data-table-selection").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                    selection: true,
                    multiSelect: true,
                    rowSelect: true,
                    keepSelection: true
                });

                //Command Buttons
                $("#data-table-command").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                });
            });
        </script>
{% endblock script %}    