django_apps/clinica/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name = 'clinica'

urlpatterns = [
    #Lista de Propietarios
    url(r'^propietarios/$', views.ClienteClinico.as_view(), name='propietarios'),
    #Busquedas
    url(r'^buscar-propietario/$', views.search_propietario, name='buscar_propietario'),
    url(r'^(?P<cliente_slug>[\w-]+)/buscar-mascota/$', views.search_mascota, name='buscar_mascota'),
    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/buscar-historial/$', views.search_historial, name='buscar_historial'),
    # Mantenimiento de Mascotas del cliente o propietario
    url(r'^(?P<cliente_slug>[\w-]+)/mascotas/$', views.ListaMascotas.as_view(), name='listar_mascotas'),
    url(r'^(?P<cliente_slug>[\w-]+)/agregar-mascota/$', views.NuevaMascota, name='agregar_mascota'),
    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/$', views.DetalleMascota.as_view(), name='detalle_mascota'),
    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/editar/$', views.EditarMascota, name='editar_mascota'),
    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/eliminar/$', views.EliminarMascota.as_view(), name='eliminar_mascota'),
    # url(r'^(?P<cliente_slug>[\w-]+)/nueva-mascota/$', views.NuevaMascota.as_view(), name='nueva_mascota'),
    # url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/editar/$', views.EditarMascota.as_view(), name='editar_mascota'),

    # Mantenimiento de Estados de las mascotas de los clientes
    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/historial/$',
        views.HistorialMascota.as_view(), name='historial_mascota'),

    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/nuevo-historial/$',
        views.NuevoEstadoMascota.as_view(), name='nuevo_estado_mascota'),

    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/(?P<estado_slug>[\w-]+)/$',
        views.DetalleEstadoMascota.as_view(), name='detalle_estado_mascota'),

    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/(?P<estado_slug>[\w-]+)/editar/$',
        views.EditarEstadoMascota.as_view(), name='editar_estado_mascota'),

    url(r'^(?P<cliente_slug>[\w-]+)/(?P<mascota_slug>[\w-]+)/(?P<estado_slug>[\w-]+)/eliminar/$',
        views.EliminarEstadoMascota.as_view(),name='eliminar_estado_mascota'),
]

django_apps/compras/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name = 'compras'

urlpatterns = [
    url(r'^$', views.ListaCompras.as_view(), name='listar_compras'),
    url(r'^search-compra/$', views.search_compra, name="buscar_compra"),
    url(r'^almacen/$', views.Almacen.as_view(), name='almacen'),
    url(r'^(?P<proveedor_slug>[\w-]+)/nueva-compra/$', views.NuevaCompraProveedor.as_view(), name='nueva_compra_proveedor'),
    url(r'^nueva-compra/$', views.NuevaCompra.as_view(), name='nueva_compra'),
    url(r'^(?P<compra_pk>[0-9]+)/$', views.DetalleCompra.as_view(), name='detalle_compra'),
    url(r'^(?P<compra_pk>[0-9]+)/editar/$', views.EditarCompra.as_view(), name='editar_compra'),
    url(r'^(?P<compra_pk>[0-9]+)/eliminar/$', views.EliminarCompra.as_view(), name='eliminar_compra'),
]

django_apps/home/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
from django.conf import settings
from django.contrib.auth.forms import AdminPasswordChangeForm
from django.core.urlresolvers import reverse_lazy
from . import views

app_name = 'home'

urlpatterns = [
    ## Gestion de usuarios
    url(r'^login/$', views.Login.as_view(), name='login_empleado'),
    url(r'^logout/$', views.Logout.as_view(), name='logout_empleado'),
    url(r'^veterinaria/$', views.ControlPanelVeterinaria.as_view(), name='inicio'),
    url(r'^empleados/$', views.ListaEmpleados.as_view(), name='listar_empleados'),
    url(r'^search-empleado/$', views.search_empleado, name="buscar_empleado"),
    url(r'^signup/$', views.CrearEmpleado.as_view(), name='signup_empleado'),
    url(r'^(?P<empleado_slug>[\w-]+)/$', views.DetalleEmpleado.as_view(), name='detalle_empleado'),

    #Cambiar Usuario creado
    # url(r'^usuario/(?P<pk>[0-9]+)/editar/$', views.EditUser,
    #     name="editar_user"),
    url(r'^(?P<empleado_slug>[\w-]+)/editar/$', views.EditarEmpleado.as_view(),
        name="editar_empleado"),

    url(r'^(?P<empleado_slug>[\w-]+)/eliminar/$', views.EliminarEmpleado.as_view(),
        name="eliminar_empleado"),
    # Cambiar Contraseña de usuario
    # url(r'^usuarios/', include('django.contrib.auth.urls')),
    url(r'^(?P<empleado_slug>[\w-]+)/password_change/$', views.password_change,
        name="password_change"),

]

django_apps/ventas/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'ventas'

urlpatterns = [
    url(r'^(?P<venta_pk>[0-9]+)/editar-venta/$', views.UpdateVenta, name='update_venta'),
    url(r'^$', views.ListaVentas.as_view(), name='listar_ventas'),
    url(r'^search-venta/$', views.search_venta, name='buscar_venta'),
    # url(r'^nuevo/$', views.NuevaVenta, name='nueva_venta'),
    url(r'^nueva-venta/$', views.CreateVenta, name='venta_nueva'),
    #
    url(r'^(?P<venta_pk>[0-9]+)/$', views.DetalleVenta.as_view(), name='detalle_venta'),
    #PDF Venta
    url(r'^(?P<venta_pk>[0-9]+)/venta-pdf/$', views.VentaPDF.as_view(), name='pdf_venta'),
    # url(r'^(?P<venta_pk>[0-9]+)/editar/$', views.EditarVenta.as_view(), name='editar_venta'),
    url(r'^(?P<venta_pk>[0-9]+)/eliminar/$', views.EliminarVenta.as_view(), name='eliminar_venta'),
]

veterinaria1/urls.py
# -*- coding: utf-8 -*-
"""veterinaria URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, patterns, url, i18n
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django_apps.home import views
import ajax_select

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('django_apps.home.urls')),
    url(r'^persona/', include('django_apps.persona.urls')),
    url(r'^inventario/', include('django_apps.inventario.urls')),
    url(r'^compras/', include('django_apps.compras.urls')),
    url(r'^ventas/', include('django_apps.ventas.urls')),
    url(r'^clinica/', include('django_apps.clinica.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ajax-select/', include('ajax_select.urls')),
    # url(r'^rosetta/', include('rosetta.urls')),
    url(r'^$', views.setlanguage, name='setlanguage'),

    #Gestion de Usuarios Empleados

    # url(r'^logout/$', views.logout_view, name='logout_empleado'),

    ## Gestion de Perfiles de Usuarios Empleados
    # url(r'^empleado/(?P<pk>[0-9]+)/$', views.DetailPerfilEmpleado.as_view(),
    #     name='detalle_perfil_empleado'),
    # url(r'^empleado/(?P<pk>[0-9]+)/editar/$', views.ActualizarPerfilEmpleado.as_view(),
    #     name='editar_perfil_empleado'),

]
handler400 = 'django_apps.home.views.bad_request'
handler403 = 'django_apps.home.views.permission_denied'
handler404 = 'django_apps.home.views.page_not_found'
handler500 = 'django_apps.home.views.server_error'

urlpatterns += i18n_patterns(
    url(r'^$', views.setlanguage, name='setlanguage'),
    # url(r'^$', home, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^persona/', include('django_apps.persona.urls')),
    url(r'^inventario/', include('django_apps.inventario.urls')),
    url(r'^compras/', include('django_apps.compras.urls')),
    url(r'^ventas/', include('django_apps.ventas.urls')),
    url(r'^clinica/', include('django_apps.clinica.urls')),
    # url(r'^', include('django_apps.home.urls')),
    # url(r'^ajax-select/', include('ajax_select.urls')),
)


# handler404 = 'views.Page_not_Found'

if settings.DEBUG:
    # urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_sistema.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block titulo %}Veterinaria Only Pets{% endblock titulo %}</title>

        <link href="{% static 'css/fullcalendar.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/sweetalert.css' %}" rel="stylesheet">
        <link href="{% static 'css/material-design-iconic-font.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/jquery.mCustomScrollbar.min.css' %}" rel="stylesheet">
            
        {% block extrahead %}{% endblock extrahead %}
        <!-- CSS -->
        <link href="{% static 'css/app_1.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/app_2.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/demo.css' %}" rel="stylesheet">
    </head>
    <body>
        <header id="header" class="clearfix" data-ma-theme="blue">
            <ul class="h-inner">
                <li class="hi-trigger ma-trigger" data-ma-action="sidebar-open" data-ma-target="#sidebar">
                    <div class="line-wrap">
                        <div class="line top"></div>
                        <div class="line center"></div>
                        <div class="line bottom"></div>
                    </div>
                </li>

                <li class="hi-logo hidden-xs">
                    <a href="{% url 'home:inicio' %}">Veterinaria Only Pets</a>
                </li>
                <li class="pull-right">
                    <ul class="hi-menu">
                        <li>
                            <a href="{% url 'home:listar_empleados' %}">
                                <span class="him-label">Empleados</span>
                            </a>                            
                        </li>
                    </ul>
                </li>

        </header>
        
        <section id="main">
            <aside id="sidebar" class="sidebar c-overflow">
                <div class="s-profile">
                    <a href="" data-ma-action="profile-menu-toggle">
                        <div class="sp-pic">
                            {% if user.is_authenticated %}
                            {% if request.user.avatar %}
                            <img src="{{request.user.avatar.url}}" alt="">
                            {% else %}
                            <img src="{% static 'img/profile-pics/4.jpg' %}" alt="">
                            {% endif %}
                            {% else %}
                            <img src="{% static 'img/user.png' %}" alt="">
                            {% endif %}
                        </div>

                        <div class="sp-info">
                            {% if user.is_authenticated %}
                            {% if request.user.first_name %}
                            {{request.user.first_name}} {{request.user.last_name}} {{request.user.second_name}}
                            {% else %}
                            {{request.user.username}}
                            {% endif %}
                            {% else %}
                            Fuera de sesión (no está autenticado)
                            {% endif %}
                            <i class="zmdi zmdi-caret-down"></i>
                        </div>
                    </a>

                    <ul class="main-menu">
                        {% if user.is_authenticated %}
                        {% if request.user.first_name %}
                        <li>
                            <a href="{% url 'home:detalle_empleado' request.user.slug %}"><i class="zmdi zmdi-account"></i> View Profile</a>
                        </li>
                        {% endif %}
                        <li>
                            <a href="{% url 'home:editar_empleado' request.user.slug %}"><i class="zmdi zmdi-settings"></i> Settings</a>
                        </li>
                        <li>
                            <a href="{% url 'home:password_change' request.user.slug %}"><i class="zmdi zmdi-key"></i> Cambiar Contraseña</a>
                        </li>
                        <li>
                            <a href="{% url 'home:logout_empleado' %}"><i class="zmdi zmdi-time-restore"></i> Logout</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{% url 'home:login_empleado' %}"><i class="zmdi zmdi-account"></i> Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>

                <ul class="main-menu">
                    <li class="active toggled">
                        <a href="{% url 'home:inicio' %}"><i class="zmdi zmdi-home"></i> {% trans "Home" %}</a>
                    </li>
                    <li class="sub-menu">
                        <a href="" data-ma-action="submenu-toggle"><i class="zmdi zmdi-assignment"></i> {% trans "Inventorio" %}</a>
                        <ul>
                            <li><a href="{% url 'inventario:listar_articulos'%}"> {% trans "Articulos"%}</a></li>
                            <li><a href="{% url 'inventario:listar_categorias' %}">Categorias</a></li>
                            <li><a href="{% url 'persona:listar_proveedores' %}">Proveedores</a></li>
                            <li><a href="{% url 'compras:almacen'%}">Almacén</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'compras:listar_compras'%}"><i class="zmdi zmdi-shopping-cart"></i> Compras</a></li>
                    <li><a href="{% url 'persona:listar_clientes' %}"><i class="zmdi zmdi-accounts-list"></i> Clientes</a></li>
                    <li><a href="{% url 'ventas:listar_ventas'%}"><i class="zmdi zmdi-money"></i> Ventas</a></li>
                    <li><a href="{% url 'clinica:propietarios'%}"><i class="zmdi zmdi-hospital"></i> Atención Clínica</a></li>
                    <li class="sub-menu">
                        <a href="" data-ma-action="submenu-toggle"><i class="zmdi zmdi-accounts"></i> Empleados</a>

                        <ul>
                            <li><a href="{% url 'home:signup_empleado'%}">Nuevo Empleado</a></li>
                            <li><a href="#">Asignar Permisos</a></li>
                        </ul>
                    </li>

                </ul>
            </aside>

            <section id="content">
                {% block producto %}
                <div class="container">
                    <!-- <div class="block-header"> -->
                    <!--     <h2>Only Pets <small>of Cannisur</small></h2> -->
                    <!-- </div> -->
                {% block profile %}
                <div class="card">
                    {% include "messages_display.html" %}
                    {% block content %}
                        <div class="card-header">
                            <h2>Damos una atención de primera
                                <small>Te Ofrecemos un servicio de calidad, contamos con buenos especialistas en el área</small>
                            </h2>
                        </div>
                        <div class="card-body card-padding" >
                            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                <!-- Indicators -->
                                <ol class="carousel-indicators">
                                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                </ol>

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner" id="section" role="listbox">
                                    <div class="item active">
                                        <img src="{% static 'img/pet/pet5.jpg' %}" alt="">
                                        <div class="carousel-caption">
                                            <h3>Estudio detallado de la mascota</h3>
                                            <p>Para empezar con un diagnóstico
                                                mas avanzado primero se le hace un
                                            chequeo médico</p>
                                        </div>
                                    </div>
                                    <div class="item">
                                        <img src="{% static 'img/pet/pet6.jpg' %}" alt="">
                                    </div>
                                    <div class="item">
                                        <img src="{% static 'img/pet/pet7.jpg' %}" alt="">
                                    </div>
                                </div>

                                <!-- Controls -->
                                <a class="left carousel-control" href="#carousel-example-generic" role="button"
                                   data-slide="prev">
                                    <span class="zmdi zmdi-chevron-left" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="right carousel-control" href="#carousel-example-generic" role="button"
                                   data-slide="next">
                                    <span class="zmdi zmdi-chevron-right" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                        </div>
                        {% endblock content %}
                    </div>
                    {% endblock profile %}

                    <div class="mini-charts">
                       
                    </div>

                    <div class="row">
                    </div>
                </div>
                    {% endblock producto %}
            </section>
        </section>
        
        <footer id="footer">
            Copyright &copy; 2016 Veterinaria Only Pets
            
            <ul class="f-menu">
                <li><a href="">Home</a></li>
                <li><a href="">Dashboard</a></li>
                <li><a href="">Reports</a></li>
                <li><a href="">Support</a></li>
                <li><a href="">Contact</a></li>
            </ul>
        </footer>

        <!-- Page Loader -->
        <div class="page-loader">
            <div class="preloader pls-blue">
                <svg class="pl-circular" viewBox="25 25 50 50">
                    <circle class="plc-path" cx="50" cy="50" r="20" />
                </svg>

                <p>Please wait...</p>
            </div>
        </div>
        
        <!-- Javascript Libraries -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        
        <script src="{% static 'js/jquery.flot.js' %}"></script>
        <script src="{% static 'js/jquery.flot.resize.js' %}"></script>
        <script src="{% static 'js/curvedLines.js' %}"></script>
        <script src="{% static 'js/jquery.sparkline.min.js' %}"></script>
        <script src="{% static 'js/jquery.easypiechart.min.js' %}"></script>
        
        <script src="{% static 'js/moment.min.js' %}"></script>
        <script src="{% static 'js/fullcalendar.min.js' %}"></script>
        <script src="{% static 'js/jquery.simpleWeather.min.js' %}"></script>
        <script src="{% static 'js/waves.min.js' %}"></script>
        <script src="{% static 'js/bootstrap-growl.min.js' %}"></script>
        <script src="{% static 'js/sweetalert.min.js' %}"></script>
        <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
        
        <!-- Placeholder for IE9 -->
        <!--[if IE 9 ]>
            <script src="vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js"></script>
            <![endif]-->
        {% block script %}{% endblock script %}

        <script src="{% static 'js/app.min.js' %}"></script>
    </body>
</html>

templates/messages_display.html
{% if messages %}
<style type="text/css">
    li{
        list-style-type: none;
    }
</style>
<div class="card-body card-padding">
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>         
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
        {% endfor %}
    </div>
</div>
{% endif %}      

templates/set-languaje.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Seleccion de Idioma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/sweetalert.css' %}" rel="stylesheet">
    <link href="{% static 'css/material-design-iconic-font.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/jquery.mCustomScrollbar.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-select.css' %}" rel="stylesheet">
    <link href="{% static 'css/nouislider.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/app_1.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/app_2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/demo.css' %}" rel="stylesheet">
    <link href="{% static 'css/languaje.css'%}" rel="stylesheet">
    <style type="text/css">

        body{
            background:url({% static 'img/blue.jpg'%});
            background-size:cover;
            background-repeat:no-repeat;
            /*font-family:sans-serif; */
            outline: 0;
        }
    </style>
</head>
<body>
    <div id='language'>
        <div class="card-header ch-alt">
           <h2 id="titulo">Veterinaria ONLY PETS</h2>
        </div>
        <figure>
            <img src="{% static 'img/pets.jpg' %}" class='img-pets'> 
        </figure>
        <form action="/i18n/setlang/" method="post">{% csrf_token %}
            <input name="next" type="hidden" value="{% url 'home:inicio' %}" />
            <div id="select">
                <p class="f-500 m-b-15 c-black">Seleciona tu idioma</p>
                <select name="language" class="selectpicker">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                    {{ language.name_local }} ({{ language.code }})
                    </option>
                    {% endfor %}
                </select><br> 
                <button type="submit" class="btn btn-default btn-icon"><i class="zmdi zmdi-arrow-forward"></i></button>
                <a data-toggle="modal" href="#modalDefault" class="btn btn-sm btn-default">Ingresar <i class="zmdi zmdi-arrow-forward"></i></a>
                <!-- <input type="submit" value="Ir" /> -->
            </div>
        </form> 
    </div>
    <div class="modal fade" id="modalDefault" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="card">
                    <div class="card-header ch-alt">
                        <h2 id='login'>Log In
                            <small>Veterianria Only Pets of Cannissur</small>
                        </h2>
                    </div>
                    <div class="card-body card-padding">
                        <div class="form-group fg-float m-b-30">
                            <div class="fg-line">
                                <input type="text" class="form-control input-sm">
                                <label class="fg-label">Username</label>
                            </div>
                        </div>
                        <div class="form-group fg-float m-b-30">
                            <div class="fg-line">
                                <input type="password" class="form-control input-sm">
                                <label class="fg-label">Password</label>
                            </div>
                        </div>
                        <button class="btn btn-info">Sig in <i class="zmdi zmdi-mail-send"></i></button>
                        <button class="btn btn-link">Cancel</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
        <footer id="menu_footer">
            Copyright &copy; 2016 Veterinaria Only Pets
            
            <ul class="f-menu">
                <li><a href="">Home</a></li>
                <li><a href="">Dashboard</a></li>
                <li><a href="">Reports</a></li>
                <li><a href="">Support</a></li>
                <li><a href="">Contact</a></li>
            </ul>
        </footer> 

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/waves.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-growl.min.js' %}"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script> 
    <script src="{% static 'js/bootstrap-select.js' %}"></script>
    <script src="{% static 'js/app.min.js' %}"></script>      
        
</body>
</html>