django_apps/home/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
from django.conf import settings
from django.contrib.auth.forms import AdminPasswordChangeForm
from django.core.urlresolvers import reverse_lazy
from . import views

app_name = 'home'

urlpatterns = [
    ## Gestion de usuarios
    url(r'^login/$', views.Login.as_view(), name='login_empleado'),
    url(r'^logout/$', views.Logout.as_view(), name='logout_empleado'),
    url(r'^veterinaria/$', views.ControlPanelVeterinaria.as_view(), name='inicio'),
    url(r'^empleados/$', views.ListaEmpleados.as_view(), name='listar_empleados'),
    url(r'^search-empleado/$', views.search_empleado, name="buscar_empleado"),
    url(r'^signup/$', views.CrearEmpleado.as_view(), name='signup_empleado'),
    url(r'^(?P<empleado_slug>[\w-]+)/$', views.DetalleEmpleado.as_view(), name='detalle_empleado'),

    #Cambiar Usuario creado
    # url(r'^usuario/(?P<pk>[0-9]+)/editar/$', views.EditUser,
    #     name="editar_user"),
    url(r'^(?P<empleado_slug>[\w-]+)/editar/$', views.EditarEmpleado.as_view(),
        name="editar_empleado"),

    url(r'^(?P<empleado_slug>[\w-]+)/eliminar/$', views.EliminarEmpleado.as_view(),
        name="eliminar_empleado"),
    # Cambiar Contraseña de usuario
    # url(r'^usuarios/', include('django.contrib.auth.urls')),
    url(r'^(?P<empleado_slug>[\w-]+)/password_change/$', views.password_change,
        name="password_change"),

]

django_apps/inventario/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

app_name = 'inventario'

urlpatterns = [
    #Búsquedas de articulos
    url(r'^search-articulo/$', views.search_articulo, name="buscar_articulo"),
    #CRUD de Articulos
    url(r'^articulos/$', views.ListarArticulos.as_view(), name='listar_articulos'),
    url(r'^articulo/crear/$', views.CrearArticulo.as_view(), name='crear_articulo'),
    url(r'^articulo/(?P<articulo_slug>[\w-]+)/$', views.DetalleArticulo.as_view(), name='detalle_articulo'),
    url(r'^articulo/(?P<articulo_slug>[\w-]+)/editar/$', views.EditarArticulo.as_view(), name='editar_articulo'),
    url(r'^articulo/(?P<articulo_slug>[\w-]+)/eliminar/$', views.EliminarArticulo.as_view(), name='eliminar_articulo'),
    #Búsquedas de Categorias
    url(r'^search-categoria/$', views.search_categoria, name="buscar_categoria"),
    #CRUD de Categorias
    url(r'^categorias/$', views.ListarCategorias.as_view(), name='listar_categorias'),
    url(r'^categoria/crear/$', views.CrearCategoria.as_view(), name='crear_categoria'),
    url(r'^categoria/(?P<categoria_slug>[\w-]+)/editar/$', views.EditarCategoria.as_view(), name='editar_categoria'),
    url(r'^categoria/(?P<categoria_slug>[\w-]+)/eliminar/$', views.EliminarCategoria.as_view(), name='eliminar_categoria'),
]

veterinaria1/urls.py
# -*- coding: utf-8 -*-
"""veterinaria URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, patterns, url, i18n
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django_apps.home import views
import ajax_select

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('django_apps.home.urls')),
    url(r'^persona/', include('django_apps.persona.urls')),
    url(r'^inventario/', include('django_apps.inventario.urls')),
    url(r'^compras/', include('django_apps.compras.urls')),
    url(r'^ventas/', include('django_apps.ventas.urls')),
    url(r'^clinica/', include('django_apps.clinica.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ajax-select/', include('ajax_select.urls')),
    # url(r'^rosetta/', include('rosetta.urls')),
    url(r'^$', views.setlanguage, name='setlanguage'),

    #Gestion de Usuarios Empleados

    # url(r'^logout/$', views.logout_view, name='logout_empleado'),

    ## Gestion de Perfiles de Usuarios Empleados
    # url(r'^empleado/(?P<pk>[0-9]+)/$', views.DetailPerfilEmpleado.as_view(),
    #     name='detalle_perfil_empleado'),
    # url(r'^empleado/(?P<pk>[0-9]+)/editar/$', views.ActualizarPerfilEmpleado.as_view(),
    #     name='editar_perfil_empleado'),

]
handler400 = 'django_apps.home.views.bad_request'
handler403 = 'django_apps.home.views.permission_denied'
handler404 = 'django_apps.home.views.page_not_found'
handler500 = 'django_apps.home.views.server_error'

urlpatterns += i18n_patterns(
    url(r'^$', views.setlanguage, name='setlanguage'),
    # url(r'^$', home, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^persona/', include('django_apps.persona.urls')),
    url(r'^inventario/', include('django_apps.inventario.urls')),
    url(r'^compras/', include('django_apps.compras.urls')),
    url(r'^ventas/', include('django_apps.ventas.urls')),
    url(r'^clinica/', include('django_apps.clinica.urls')),
    # url(r'^', include('django_apps.home.urls')),
    # url(r'^ajax-select/', include('ajax_select.urls')),
)


# handler404 = 'views.Page_not_Found'

if settings.DEBUG:
    # urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_apps/inventario/models.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django_apps.core.models import TimeStampedModel
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django_countries.fields import CountryField
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.core.urlresolvers import reverse

def upload_location(instance, filename):
    # filebase, extension = filename.split(".")
    # return "%s/%s.%s" %(instance.id, instance.id, filename)
    return "%s/%s" %(instance.id, filename)

@python_2_unicode_compatible
class Articulo(TimeStampedModel):
    codigo = models.CharField(_('Código'), max_length=13, editable=False)
    nombre = models.CharField(_('Nombre'), max_length=100)
    slug = models.SlugField(unique=True)
    marca = models.CharField(_('Marca'), max_length=100)
    p_compra = models.DecimalField(_('Precio de Compra'), max_digits=4, decimal_places=2)
    p_venta = models.DecimalField(_('Precio de Venta'), max_digits=4, decimal_places=2)
    avatar = models.ImageField(upload_to=upload_location)

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('inventario:detalle_articulo', kwargs={'articulo_slug':self.slug})

    def save(self, *args, **kwargs):
        #Hallando el dígito verificador
        a = '7752016'
        i = Articulo.objects.count()
        if i==None:
            b = 1
        else:
            b = i+1
        b = '{0:05}'.format(b)
        s = a + b
        dv = a + b
        s = " ".join(s)
        s = s.split(" ")
        n = [int(s[i]) for i in range(len(s)) if i%2!=0]
        n = sum(n)
        n = n * 3
        m = [int(s[i]) for i in range(len(s)) if i%2==0]
        m= sum(m)
        x = n + m
        if x % 10 == 0:
            res = 0
            self.codigo = '{0}{1}'.format(dv,res)
        else:
            r = (x + 9) - ((x + 9)%10)
            res = r - x
            self.codigo = '{0}{1}'.format(dv,res)
        super(Articulo, self).save(*args,**kwargs)

    class Meta:
        ordering = ['-nombre']
        verbose_name_plural = 'Articulos'

def create_slug_articulo(instance, new_slug=None):
    slug = slugify(instance.nombre)
    if new_slug is not None:
        slug = new_slug
    qs = Articulo.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug_articulo(instance, new_slug=new_slug)
    return slug

def pre_save_articulo_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug_articulo(instance)

pre_save.connect(pre_save_articulo_receiver, sender=Articulo)

class Categoria(models.Model):
    nombre = models.CharField(_('Categoría'), max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('inventario:listar_categorias')

    class Meta:
        ordering = ['-id']
        verbose_name_plural = 'Categorías'

def create_slug_categoria(instance, new_slug=None):
    slug = slugify(instance.nombre)
    if new_slug is not None:
        slug = new_slug
    qs = Categoria.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug_categoria(instance, new_slug=new_slug)
    return slug

def pre_save_categoria_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug_categoria(instance)

pre_save.connect(pre_save_categoria_receiver, sender=Categoria)

django_apps/inventario/forms.py
from django import forms

from .models import Articulo, Categoria

class ArticuloForm(forms.ModelForm):
    class Meta:
        model = Articulo
        fields = ['nombre','marca','p_compra','p_venta','avatar']

    def __init__(self, *args, **kwargs):
        super(ArticuloForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs.update({'class' : 'form-control'})
        self.fields['marca'].widget.attrs.update({'class' : 'form-control'})
        self.fields['p_compra'].widget.attrs.update({'class' : 'form-control input-mask','placeholder':'eg: 000.000.000.000.000,00'})
        self.fields['p_venta'].widget.attrs.update({'class' : 'form-control input-mask','placeholder':'eg: 000.000.000.000.000,00'})

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre']
    def __init__(self, *args, **kwargs):
        super(CategoriaForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs.update({'class' : 'form-control'})

django_apps/inventario/views.py
from django.shortcuts import render, render_to_response
from django.db.models import Q
from django.views.generic import *
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from django.core.urlresolvers import reverse
from django.contrib.messages.views import SuccessMessageMixin
from django_apps.home.views import LoginRequiredMixin
from .models import Articulo, Categoria
from .forms import ArticuloForm, CategoriaForm

@login_required(login_url='home:login_empleado')
def search_articulo(request):
    query = request.GET.get('q', '')
    if query:
        qset = (
            Q(nombre__icontains=query)|
            Q(marca__icontains=query)|
            Q(p_compra__icontains=query)|
            Q(p_venta__icontains=query)
        )
        results = Articulo.objects.filter(qset).distinct()
    else:
        results = []
    return render_to_response("inventario/search_articulo.html", {
        "results": results,
        "query": query
    })

@login_required(login_url='home:login_empleado')
def search_categoria(request):
    query = request.GET.get('q', '')
    if query:
        qset = (
            Q(nombre__icontains=query)
        )
        results = Categoria.objects.filter(qset).distinct()
    else:
        results = []
    return render_to_response("inventario/search_categoria.html", {
        "results": results,
        "query": query
    })
class ListarArticulos(LoginRequiredMixin, ListView):
    model = Articulo
    context_object_name = 'listar_articulos'
    paginate_by = 10
    template_name = 'inventario/articulos.html'

class CrearArticulo(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = Articulo
    form_class = ArticuloForm
    success_message = 'El articulo %(nombre)s se ha creado correctamente'
    slug_url_kwarg = 'articulo_slug'
    template_name = 'inventario/crear_articulo.html'

class DetalleArticulo(LoginRequiredMixin, DetailView):
    model = Articulo
    template_name = 'inventario/detalle_articulo.html'
    slug_url_kwarg = 'articulo_slug'

class EditarArticulo(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = Articulo
    form_class = ArticuloForm
    slug_url_kwarg = 'articulo_slug'
    success_message = 'El articulo %(nombre)s se ha editado correctamente'
    template_name = 'inventario/crear_articulo.html'

class EliminarArticulo(LoginRequiredMixin,SuccessMessageMixin,DeleteView):
    model = Articulo
    slug_url_kwarg = 'articulo_slug'
    success_url = reverse_lazy('inventario:listar_articulos')
    success_message = 'El articulo %(nombre)s eliminado correctamente'
    template_name = 'inventario/confirmar_eliminar_articulo.html'

class ListarCategorias(LoginRequiredMixin, ListView):
    model = Categoria
    paginate_by = 10
    context_object_name = 'listar_categorias'
    template_name = 'inventario/categorias.html'

class CrearCategoria(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = Categoria
    form_class = CategoriaForm
    slug_url_kwarg = 'categoria_slug'
    success_message = 'Categoria %(nombre)s se ha creado correctamente'
    template_name = 'inventario/crear_categoria.html'

class EditarCategoria(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = Categoria
    form_class = CategoriaForm
    slug_url_kwarg = 'categoria_slug'
    success_message = 'Categoria %(nombre)s  se ha editado correctamente'
    template_name = 'inventario/crear_categoria.html'

class EliminarCategoria(LoginRequiredMixin, SuccessMessageMixin,DeleteView):
    model = Categoria
    slug_url_kwarg = 'categoria_slug'
    success_message = 'Categoria %(nombre)s eliminado correctamente'
    template_name = 'inventario/confirmar_eliminar_categoria.html'
    success_url = reverse_lazy('inventario:listar_categorias')

templates/inventario/articulos.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<link href="{% static 'css/jquery.bootgrid.min.css' %}" rel="stylesheet">
<style type="text/css">
    #buscar{
        width:36%;
    }
    #buscar input{
        width:25em;;
    }
    .fg-line, #btn{
        position:relative;
        display:inline-block;
    }
    .pag2{
        width:30%;
        padding:0.5em 1em 0.5em 1em;
        text-align:center;
        border: 1px solid #cdcdcd;
    }
    #fast{
        margin-left:30em;    
    }
    #articulo {
        text-align:center;
        font-size:2em;
    }
</style>
{% endblock extrahead %}
{% block content %}
<div class="card-header ch-alt bgm-cyan">
    <h2 id="articulo">Artículos</h2>
</div>   
<div class="card-body card-padding">   
    <div class="btn-demo">
        <table id="data-table" class="table table-striped table-vmiddle">
            {% if listar_articulos %}
            <div class="ms-search hidden-xs">
                <form action="{% url 'inventario:buscar_articulo' %}" method="GET">
                    <div class="row">
                        <div id="buscar" class="col-sm-4">
                            <div class="input-group">
                                <i type="submit" class="zmdi zmdi-search"></i>
                                <input type="text" name="q" value="{{ query|escape }}" class="form-control" placeholder="Search...">
                            </div>
                        </div>
                        <div id="buscar"class="col-sm-4">
                            <div class="input-group">
                                <button type="submit" id="btn" class="btn btn-info">Enviar <i class="zmdi zmdi-mail-send"></i></button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            {% endif %}
            <thead>
                {% if listar_articulos %}
                <tr>
                    <th data-column-id="id" data-type="numeric">ID</th> 
                    <th data-column-id="sender">Articulo</th> 
                    <th data-column-id="names" data-order="desc">Marca</th> 
                    <th data-column-slug="commands" data-formatter="commands" data-sortable="false">Acciones</th>
                </tr>  
                {% endif %}
            </thead>
            <tbody>
                {% for i in listar_articulos %}
                <tr>
                    <td>{{i.id}}</td> 
                    <td>{{i.nombre}}</td> 
                    <td>{{i.marca}}</td> 
                    <td> 
                        <a href="{% url 'inventario:editar_articulo' i.slug %}"class="btn btn-primary btn-icon" ><i class="zmdi zmdi-edit"></i></a>
                        <a href="{% url 'inventario:detalle_articulo' i.slug %}" class="btn btn-info btn-icon"><i class="zmdi zmdi-assignment"></i></a>
                        <a href="{% url 'inventario:eliminar_articulo' i.slug %}" class="btn bgm-deeporange btn-icon"><i class="zmdi zmdi-delete"></i></a>
                    </td>
                </tr>
                {% endfor %}
               
            </tbody>
        </table>
        <a href="{% url 'inventario:crear_articulo' %}" class="btn btn-primary btn-block">Agregar Nuevo Articulo</a>
    </div>          
    {% if is_paginated %}
    <div class="row">
    <div id="fast" class="col-sm-6">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}"><i class="zmdi zmdi-fast-rewind "></i></a></li>
            {% else %}
            <li class="disabled"><a href="#!"><i class="zmdi zmdi-fast-rewind "></i></a></li>
            {% endif %}
            <li class="active"><a href="">{{page_obj.number}}</a></li>
            {% if page_obj.has_next %}
            <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}"><i class="zmdi zmdi-fast-forward"></i></a></li>
            {% else %}
            <li class="disabled"><a href="#!"><i class="zmdi zmdi-fast-forward"></i></a></li>
            {% endif %}
        </ul>
    </div>
    <div id="fast"class="col-sm-6 infoBar">
        <div class="pag2">
            Page {{ page_obj.number }} of {{ paginator.num_pages }}.
        </div>
    </div>
    </div>
    {% endif %}
</div>
{% endblock content %}
{% block script %}
<script src="{% static 'js/jquery.bootgrid.updated.min.js' %}"></script>
 <script type="text/javascript">
            $(document).ready(function(){
                //Basic Example
                $("#data-table-basic").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                });

                //Selection
                $("#data-table-selection").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                    selection: true,
                    multiSelect: true,
                    rowSelect: true,
                    keepSelection: true
                });

                //Command Buttons
                $("#data-table-command").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                });
            });
        </script>
{% endblock script %} 

templates/inventario/confirmar_eliminar_articulo.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<style type="text/css">
    #eliminar{
        width:50%;
        margin: 0 auto;
    }
    #borrado{
        text-align: center;
    }
</style>
{% endblock extrahead %}
{% block content %}
<div class="card-header">
    <h2 id="borrado">Borrado de Artículo</h2>
</div>   
<div class="card-body card-padding">    
    <div id="eliminar">
        <div class="bs-item z-depth-5">
            <form method="post">{% csrf_token %} 
                <p class="f-500 c-black m-b-15"> ¿Realmente quieres borrar a <strong>{{object.nombre }}</strong>"?</p> 
                <button type="submit" class="btn btn-primary btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-check"></i></button>
                <button class="btn bgm-deeporange btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-close"></i></button>
            </form> 
        </div>
    </div>
{% endblock content %}  

templates/inventario/confirmar_eliminar_categoria.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% load i18n %}
{% block extrahead %}
<style type="text/css">
    #eliminar{
        width:50%;
        margin: 0 auto;
    }
    #borrado{
        text-align: center;
    }
</style>
{% endblock extrahead %}
{% block content %}
<div class="card-header">
    <h2 id="borrado">Borrado de Categoría</h2>
</div>   
<div class="card-body card-padding">    
    <div id="eliminar">
        <div class="bs-item z-depth-5">
            <form method="post">{% csrf_token %} 
                <p class="f-500 c-black m-b-15"> ¿Realmente quieres borrar a <strong>{{object.nombre }}</strong>"?</p> 
                <button type="submit" class="btn btn-primary btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-check"></i></button>
                <a href="{% url 'inventario:listar_categorias' %}" class="btn bgm-deeporange btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-close"></i></a>
            </form> 
        </div>
    </div>
{% endblock content %} 

templates/inventario/search_articulo.html
{% extends "base_sistema.html" %}
{% load staticfiles %}
{% load i18n %}
{% block titulo %}
Search{% if query %} Resultados{% endif %}
{% endblock titulo %}
{% block extrahead %}
<link href="{% static 'css/jquery.bootgrid.min.css' %}" rel="stylesheet">
<style type="text/css">
    #buscar{
        width:36%;
    }
    #buscar input{
        width:25em;;
    }
    .fg-line{
    }
    .fg-line, #btn{
        position:relative;
        display:inline-block;
    }
    #btn{
        margin-right:1em;
    }
</style>
{% endblock extrahead %}
{% block content %}
<div class="card-header">
    <h2>Empleados</h2>
</div>   
<div class="card-body card-padding">   
    <div class="btn-demo">
        <table id="data-table" class="table table-striped table-vmiddle">
            <div class="ms-search hidden-xs">
                <form action="{% url 'inventario:buscar_articulo' %}" method="GET">
                    <div class="row">
                        <div id="buscar" class="col-sm-4">
                            <div class="input-group">
                                <i type="submit" class="zmdi zmdi-search"></i>
                                <input type="text" name="q" value="{{ query|escape }}" class="form-control" placeholder="Search...">
                            </div>
                        </div>
                        <div id="buscar"class="col-sm-4">
                            <div class="input-group">
                                <button type="submit" id="btn" class="btn btn-info">Enviar <i class="zmdi zmdi-mail-send"></i></button>
                                <a href="{% url 'inventario:listar_articulos' %}"  type="submit" id="btn" class="btn  btn-default">Volver <i class="zmdi zmdi-mail-reply"></i></a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            {% if query %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                Resultados de busqueda de Articulos
            </div>
            {% if results %}
            <thead>
                <tr>
                    <th data-column-id="id" data-type="numeric">ID</th> 
                    <th data-column-id="sender">Artículo</th> 
                    <th data-column-id="names" data-order="desc">Marca</th> 
                    <th data-column-slug="commands" data-formatter="commands" data-sortable="false">Acciones</th>
                </tr>  
            </thead>
            <tbody>
                {% for i in results %}
                <tr>
                    <td>{{i.id}}</td> 
                    <td>{{i.nombre}}</td> 
                    <td>{{i.marca}}</td> 
                    <td> 
                        <a href="{% url 'home:editar_articulo' i.slug %}"class="btn btn-primary btn-icon" >
                            <i class="zmdi zmdi-edit"></i>
                        </a>
                        <a href="{% url 'home:detalle_articulo' i.slug %}"> 
                            <button class="btn btn-info btn-icon"><i class="zmdi zmdi-assignment"></i></button>
                        </a> 
                        <a href="{% url 'home:eliminar_articulo' i.slug %}"> 
                            <button class="btn bgm-deeporange btn-icon"><i class="zmdi zmdi-delete"></i></button>
                        </a> 
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                 <div class="col-sm-3">
                    <p class="f-500 c-black m-b-20">Lo sentimos no hay
                        empleados, si desea agregar ...
                        <a href="{% url 'inventario:crear_articulo' %}" class="btn
                            btn-info" id="sa-warning">Click me</a>
                </div> 
            {% endif %}
            {% endif %}
            </tbody>
        </table>
        <a href="{% url 'inventario:crear_articulo' %}" class="btn btn-primary btn-block">Agregar Nuevo Articulo</a>
    </div>
</div>
{% endblock content %}
{% block script %}
<script src="{% static 'js/jquery.bootgrid.updated.min.js' %}"></script>
 <script type="text/javascript">
            $(document).ready(function(){
                //Basic Example
                $("#data-table-basic").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                });

                //Selection
                $("#data-table-selection").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },
                    selection: true,
                    multiSelect: true,
                    rowSelect: true,
                    keepSelection: true
                });

                //Command Buttons
                $("#data-table-command").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-sort-amount-desc',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-sort-amount-asc'
                    },

                });
            });
        </script>
{% endblock script %} 